import type { Config } from "tailwindcss";

/**
 * Design system ported from stitch_prd_visual_design (Modern Utility v2 —
 * "Vibrant Indigo" palette). All tokens come from the mockup tailwind-config
 * blocks so the app matches the approved screens.
 */
const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tiktok-cyan": "#00f2ea",
        surface: "#f7f9fb",
        "tertiary-fixed": "#c9e6ff",
        "primary-container": "#6063ee",
        "on-tertiary-container": "#fcfcff",
        "success-green": "#22c55e",
        "inverse-on-surface": "#eff1f3",
        "outline-variant": "#c7c4d7",
        "on-surface": "#191c1e",
        "tertiary-fixed-dim": "#89ceff",
        "tertiary-container": "#007cb1",
        secondary: "#505f76",
        "tiktok-magenta": "#ff0050",
        "secondary-fixed": "#d3e4fe",
        "inverse-primary": "#c0c1ff",
        outline: "#767586",
        "on-primary-fixed": "#07006c",
        "surface-container": "#eceef0",
        error: "#ba1a1a",
        tertiary: "#00628d",
        primary: "#4648d4",
        "primary-fixed": "#e1e0ff",
        "surface-tint": "#494bd6",
        "surface-container-low": "#f2f4f6",
        "primary-fixed-dim": "#c0c1ff",
        "on-background": "#191c1e",
        "instagram-gradient-start": "#405de6",
        "on-tertiary-fixed": "#001e2f",
        "on-primary": "#ffffff",
        "on-surface-variant": "#464554",
        "error-container": "#ffdad6",
        "inverse-surface": "#2d3133",
        "on-error-container": "#93000a",
        background: "#f7f9fb",
        "surface-container-highest": "#e0e3e5",
        "surface-container-high": "#e6e8ea",
        "on-tertiary": "#ffffff",
        "instagram-gradient-end": "#c13584",
        "on-tertiary-fixed-variant": "#004c6e",
        "warning-amber": "#f59e0b",
        "on-secondary-container": "#54647a",
        "surface-dim": "#d8dadc",
        "youtube-red": "#ff0000",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#38485d",
        "on-secondary-fixed": "#0b1c30",
        "on-primary-container": "#fffbff",
        "on-primary-fixed-variant": "#2f2ebe",
        "secondary-container": "#d0e1fb",
        "secondary-fixed-dim": "#b7c8e1",
        "error-red": "#ef4444",
        "surface-bright": "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e0e3e5",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-margin": "1rem",
        "stack-md": "1rem",
        gutter: "1rem",
        "touch-target-min": "48px",
        "stack-sm": "0.5rem",
        "stack-lg": "1.5rem",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "mono-label": ["Inter", "monospace"],
        "headline-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "mono-label": ["13px", { lineHeight: "18px", fontWeight: "500" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
      },
      keyframes: {
        shimmer: {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(100%)" },
        },
        slideUp: {
          from: { transform: "translateY(100%)" },
          to: { transform: "translateY(0)" },
        },
        fadeIn: {
          from: { opacity: "0", transform: "translateY(4px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        shimmer: "shimmer 1.5s infinite linear",
        "slide-up": "slideUp 0.3s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "fade-in": "fadeIn 0.3s ease-out",
      },
    },
  },
  plugins: [],
};

export default config;
